name: AENA's

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Environment Variables
        run: |
          echo "KERNEL_SOURCE=https://github.com/IamCodebreaker/android_kernel_samsung_exynos5420.git" >> $GITHUB_ENV
          echo "KERNEL_SOURCE_BRANCH=lineage-17.1" >> $GITHUB_ENV
          echo "KERNEL_TARGET=lineageos_ha3g" >> $GITHUB_ENV
          echo "ANYKERNEL_SOURCE=https://github.com/osm0sis/AnyKernel3.git" >> $GITHUB_ENV
          echo "ANYKERNEL_SOURCE_BRANCH=master" >> $GITHUB_ENV

      - name: Clone GCC 4.8 Toolchain
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-eabi-4.8.git arm-eabi-4.8
          echo "$GITHUB_WORKSPACE/arm-eabi-4.8/bin" >> $GITHUB_PATH

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} kernel-source

      - name: Create Output Directory
        run: mkdir -p out

      - name: Clean Kernel Source Tree
        run: |
          make -C kernel-source ARCH=arm O=../out distclean

      - name: Build Kernel
        run: |
          export KBUILD_BUILD_USER="BUGGY"
          export KBUILD_BUILD_HOST="github"
          export PATH="$GITHUB_WORKSPACE/arm-eabi-4.8/bin:$PATH"
          make -C kernel-source \
               ARCH=arm \
               O=../out \
               CROSS_COMPILE=arm-eabi- \
               ${{ env.KERNEL_TARGET }}_defconfig
          make -C kernel-source -j$(nproc) \
               ARCH=arm \
               O=../out \
               CROSS_COMPILE=arm-eabi-

      - name: Package Kernel with AnyKernel3
        run: |
          git clone --depth=1 ${{ env.ANYKERNEL_SOURCE }} -b ${{ env.ANYKERNEL_SOURCE_BRANCH }} AnyKernel3
          rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
          if [[ -f out/arch/arm/boot/zImage ]]; then
            cp out/arch/arm/boot/zImage AnyKernel3/zImage
          fi

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ha3g_kernel
          path: AnyKernel3/*
