name: Kernel Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc \
            bison \
            flex \
            libssl-dev \
            make \
            libc6-dev \
            libncurses5-dev \
            wget \
            tar

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_kernel_samsung_exynos5420.git -b lineage-17.1 kernel-source

      - name: Download and Extract GCC Toolchain
        run: |
          wget -q https://launchpad.net/gcc-arm-embedded/4.8/4.8-2014-q3-update/+download/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
          tar -xjf gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
          mv gcc-arm-none-eabi-4_8-2014q3 arm-eabi-4.8

      - name: Set Environment Variables
        run: |
          echo "PATH=$GITHUB_WORKSPACE/arm-eabi-4.8/bin:$PATH" >> $GITHUB_ENV
          echo "CROSS_COMPILE=arm-none-eabi-" >> $GITHUB_ENV
          echo "ARCH=arm" >> $GITHUB_ENV

      - name: Create Output Directory
        run: |
          mkdir -p out

      - name: Configure Kernel
        run: |
          cd kernel-source
          make O=../out rosemary_defconfig

      - name: Build Kernel
        run: |
          cd kernel-source
          make O=../out -j$(nproc)
