name: AENA's Kernel Build

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: |
          # Load AnyKernel3 repo URL & branch
          echo "ANYKERNEL_SOURCE=$(grep -w ANYKERNEL_SOURCE config.env | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "ANYKERNEL_SOURCE_BRANCH=$(grep -w ANYKERNEL_SOURCE_BRANCH config.env | cut -d '=' -f2)" >> $GITHUB_ENV

          # Existing kernel environment
          echo "KERNEL_SOURCE=$(grep -w KERNEL_SOURCE config.env | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "KERNEL_SOURCE_BRANCH=$(grep -w KERNEL_SOURCE_BRANCH config.env | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "KERNEL_TARGET=$(grep -w KERNEL_TARGET config.env | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "BUILD_ARGS=$(grep -w BUILD_ARGS config.env | cut -d ':' -f2)" >> $GITHUB_ENV

      - name: Pull toolchain
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm-linux-androideabi-4.9

      - name: Pull kernel source
        run: |
          git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} kernel-source
          echo "KERNEL_VERSION=$(sed -n 's/.*CONFIG_LOCALVERSION=\"\([^\"]*\)\".*/\1/p' \
            kernel-source/arch/arm/configs/${{ env.KERNEL_TARGET }}_defconfig | sed 's/^\\.//')" >> $GITHUB_ENV

      - name: Clean kernel source tree
        run: |
          make -C kernel-source ARCH=arm distclean

      - name: Build kernel
        run: |
          export KBUILD_BUILD_USER="BUGGY"
          export KBUILD_BUILD_HOST="github"
          export PATH="$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin:$PATH"
          make -C kernel-source \
               ARCH=arm \
               O=../out \
               ${{ env.BUILD_ARGS }} \
               CROSS_COMPILE=arm-linux-androideabi- \
               ${{ env.KERNEL_TARGET }}_defconfig
          make -C kernel-source -j$(( $(getconf _NPROCESSORS_ONLN) * 2 )) \
               ARCH=arm \
               O=../out \
               ${{ env.BUILD_ARGS }} \
               CROSS_COMPILE=arm-linux-androideabi-

      - name: Package kernel
        run: |
          git clone --depth=1 ${{ env.ANYKERNEL_SOURCE }} -b ${{ env.ANYKERNEL_SOURCE_BRANCH }} AnyKernel3 && rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
          if [[ -f out/arch/arm/boot/zImage ]]; then
            cp out/arch/arm/boot/zImage AnyKernel3/zImage
          fi
          if [ -f out/arch/arm/boot/dt.img ]; then
            cp out/arch/arm/boot/dt.img AnyKernel3/dt.img
          fi

      - name: Upload kernel to artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KERNEL_VERSION }}_${{ env.KERNEL_TARGET }}
          path: AnyKernel3/*
